spring:
  datasource:
    url: jdbc:mysql://localhost:3306/quartzpoc
    username: root
    password: topsecret
    driver-class-name: org.mariadb.jdbc.Driver
org:
  quartz:
    scheduler:
      instanceName: spring-boot-quartz-demo
      instanceId: AUTO
    threadPool:
      threadCount: 5
job:
  startDelay: 0
  repeatInterval: 60000
  description: Sample job
  key: StatisticsJob